### ISSUE TITLE
Error After Rebooting Server with Expand_World

### ISSUE THREAD

**Issue by CalebBartle** [JereKuusela/valheim-expand_world#23] opened 2023-11-07 00:47 UTC
Jerekuusela, First off, you have some seriously amazing mods that allow us to do some really awesome things on our server.

I'm seeing an issue with our world in particular where when we try to utilize Expand World, after every server reboot, we get the following error after the server attempts to come back online:
11/04/2023 00:44:30: Console: [Error  : Unity Log] 11/04/2023 00:44:30: Exception while loading world A:\Valheim-VikingWarriors\Worlds/worlds_local/VikingWarriors.db:System.ArgumentOutOfRangeException: Non-negative number required.
The server then fails to boot and continually tries to restart and ends up performing the same error shown in the log.

We were able to get a workaround by essentially using the VikingWarriors.db.old and replacing to .db, but there appears to be something happening when the server is shutdown where the .db gets corrupted when using the Expand World mod. It seems like when it's shutdown, the .DB becomes unusable and the db.old appears to be still valid because the .db was not currently open during the last save so it wouldn't be impacted by corrupted by a dirty shutdown. Any insight would help, thank you!

**Comment by JereKuusela** [comment] 2023-12-06 17:14
Sounds like the old ZDO corruption thing caused by some mods. That has been fixed in the base game.

**Closed as completed** 2023-12-06 17:14 UTC
